name = "GenesisCgToolBase"
uuid = "76861f38-1ee2-4c38-b3af-54166ee560e5"
authors = ["Cheng Tan", "Diego Ugarte"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
